# Generated by Django 2.0.5 on 2018-07-22 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('thumbnail', models.URLField(null=True, verbose_name='thumbnail')),
                ('price', models.FloatField(null=True, verbose_name='price')),
                ('stock', models.PositiveIntegerField(null=True, verbose_name='stock')),
                ('product_description', models.TextField(null=True, verbose_name='product_description')),
                ('upc', models.CharField(max_length=255, null=True, verbose_name='upc')),
                ('url', models.URLField(null=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.BookCategory', verbose_name='category'),
        ),
    ]
